route:
  group_by: ['alertname','instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram-infra'
  routes:
    - match:
        service: web
      receiver: 'telegram-web'
    - match:
        service: infra
      receiver: 'telegram-infra'
receivers:
  - name: 'telegram-infra'
    telegram_configs:
      - bot_token: 
        api_url: https://api.telegram.org
        chat_id: 
        parse_mode: ''
        message: '{{ template "telegram.message" . }}'
  - name: 'telegram-web'
    telegram_configs:
      - bot_token:
        api_url: https://api.telegram.org
        chat_id: 
        parse_mode: ''
        message: '{{ template "telegram.message" . }}'

templates:
- /etc/alertmanager/telegram.tmpl

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
